const WORKSHOP_STYLES: Record<string, string> = {
  'affiliation-grid': [
    '[display:grid]!',
    '[gap:10px]!',
  ].join(' '),
  'affiliation-grid--participants': [
    '[&.affiliation-grid--participants]:[grid-template-columns:repeat(3,_minmax(0,_1fr))]!',
    '[&_.affiliation-tile]:[grid-template-rows:132px_minmax(58px,_auto)]!',
    '[&_.ws-affiliation-tile--media]:[padding:12px_14px]!',
    '[&_.ws-affiliation-tile--name]:[min-height:0]!',
    'max-[960px]:[&.affiliation-grid--participants]:[grid-template-columns:repeat(2,_minmax(0,_1fr))]!',
    'max-[640px]:[&_.affiliation-tile]:[grid-template-rows:112px_minmax(54px,_auto)]!',
    'max-[640px]:[&.affiliation-grid--participants]:[grid-template-columns:1fr]!',
  ].join(' '),
  'affiliation-group': [
    '[display:grid]!',
    '[gap:10px]!',
  ].join(' '),
  'affiliation-group--is-hidden': [
    '[&.affiliation-group--is-hidden]:[display:none]!',
  ].join(' '),
  'affiliation-group__title': [
    '[margin:0]!',
    '[color:#eef5ff]!',
    '[font-size:12px]!',
    '[font-weight:700]!',
    '[letter-spacing:0.09em]!',
    '[text-transform:uppercase]!',
    'max-[640px]:[font-size:11px]!',
  ].join(' '),
  'affiliation-showcase': [
    '[margin:18px_0_24px]!',
    '[display:grid]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[gap:18px]!',
    'max-[640px]:[gap:16px]!',
  ].join(' '),
  'affiliation-tile': [
    '[display:grid]!',
    '[align-items:start]!',
    '[height:100%]!',
    '[gap:8px]!',
    '[padding:10px_10px_12px]!',
    '[border-radius:14px]!',
    '[background:rgba(255,255,255,0.035)]!',
    '[border:1px_solid_rgba(255,255,255,0.08)]!',
    '[.affiliation-grid--organizers_&]:[grid-template-rows:136px_minmax(54px,_auto)]!',
    'max-[640px]:[padding:10px]!',
    'max-[640px]:[border-radius:12px]!',
    'max-[640px]:[.affiliation-grid--organizers_&]:[grid-template-rows:118px_minmax(50px,_auto)]!',
  ].join(' '),
  'affiliation-tile__logo': [
    '[display:block]!',
    '[width:100%]!',
    '[max-width:100%]!',
    '[max-height:100%]!',
    '[object-fit:contain]!',
    '[object-position:center]!',
  ].join(' '),
  'affiliation-tile__logo--participant': [
    '[&.ws-affiliation-tile--logo--participant]:[width:100%]!',
    '[&.ws-affiliation-tile--logo--participant]:[max-width:80%]!',
    '[&.ws-affiliation-tile--logo--participant]:[max-height:74px]!',
    '[&.ws-affiliation-tile--logo--participant]:[filter:drop-shadow(0_8px_18px_rgba(0,0,0,0.18))]!',
    'max-[840px]:[&.ws-affiliation-tile--logo--participant]:[max-width:82%]!',
    'max-[840px]:[&.ws-affiliation-tile--logo--participant]:[max-height:68px]!',
    'max-[640px]:[&.ws-affiliation-tile--logo--participant]:[max-width:84%]!',
    'max-[640px]:[&.ws-affiliation-tile--logo--participant]:[max-height:62px]!',
  ].join(' '),
  'affiliation-tile__logo--participant-crest': [
    '[&.ws-affiliation-tile--logo--participant-crest]:[max-width:56%]!',
    '[&.ws-affiliation-tile--logo--participant-crest]:[max-height:88px]!',
    'max-[840px]:[&.ws-affiliation-tile--logo--participant-crest]:[max-width:58%]!',
    'max-[840px]:[&.ws-affiliation-tile--logo--participant-crest]:[max-height:78px]!',
    'max-[640px]:[&.ws-affiliation-tile--logo--participant-crest]:[max-width:60%]!',
    'max-[640px]:[&.ws-affiliation-tile--logo--participant-crest]:[max-height:70px]!',
  ].join(' '),
  'affiliation-tile__logo--participant-harvard': [
    '[&.ws-affiliation-tile--logo--participant-harvard]:[max-width:58%]!',
    '[&.ws-affiliation-tile--logo--participant-harvard]:[max-height:96px]!',
    'max-[840px]:[&.ws-affiliation-tile--logo--participant-harvard]:[max-width:60%]!',
    'max-[840px]:[&.ws-affiliation-tile--logo--participant-harvard]:[max-height:84px]!',
    'max-[640px]:[&.ws-affiliation-tile--logo--participant-harvard]:[max-width:62%]!',
    'max-[640px]:[&.ws-affiliation-tile--logo--participant-harvard]:[max-height:74px]!',
  ].join(' '),
  'affiliation-tile__media': [
    '[width:100%]!',
    '[height:100%]!',
    '[min-height:0]!',
    '[display:flex]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[padding:8px_10px]!',
    '[border-radius:12px]!',
    '[background:rgba(255,255,255,0.98)]!',
    '[overflow:hidden]!',
    '[.affiliation-grid--organizers_&]:[padding:14px_18px]!',
    'max-[840px]:[min-height:0]!',
    'max-[640px]:[padding:7px_8px]!',
    'max-[640px]:[border-radius:10px]!',
  ].join(' '),
  'affiliation-tile__media--dark': [
    '[&.ws-affiliation-tile--media--dark]:[background:linear-gradient(145deg,_rgba(13,_19,_33,_0.98),_rgba(24,_34,_56,_0.98))]!',
  ].join(' '),
  'affiliation-tile__media--participant': [
    '[&.ws-affiliation-tile--media--participant]:[background:linear-gradient(145deg,_rgba(16,_22,_34,_0.96),_rgba(31,_40,_58,_0.93))]!',
    '[&.ws-affiliation-tile--media--participant]:[border:1px_solid_rgba(255,255,255,0.05)]!',
    '[&.ws-affiliation-tile--media--participant]:[box-shadow:inset_0_0_0_1px_rgba(255,255,255,0.025)]!',
  ].join(' '),
  'affiliation-tile__name': [
    '[margin:0]!',
    '[display:flex]!',
    '[align-items:flex-start]!',
    '[justify-content:center]!',
    '[padding-top:2px]!',
    '[width:100%]!',
    '[color:#dce7f5]!',
    '[font-size:12.5px]!',
    '[line-height:1.38]!',
    '[font-weight:600]!',
    '[text-align:center]!',
    '[text-wrap:balance]!',
    '[.affiliation-grid--organizers_&]:[min-height:0]!',
    '[.affiliation-tile--text-only_&]:[color:#f0f6ff]!',
    'max-[640px]:[font-size:12px]!',
    '[&.ws-affiliation-tile--name]:[font-size:12.5px]!',
    '[&.ws-affiliation-tile--name]:[line-height:1.38]!',
    'max-[640px]:[&.ws-affiliation-tile--name]:[font-size:12px]!',
  ].join(' '),
  'agenda-snapshot': [
    '[display:grid]!',
    '[gap:12px]!',
    '[margin-bottom:12px]!',
    'max-[640px]:[gap:10px]!',
  ].join(' '),
  'agenda-snapshot__item': [
    '[display:grid]!',
    '[grid-template-columns:132px_1fr]!',
    '[gap:14px]!',
    '[padding:14px_16px]!',
    '[border-radius:14px]!',
    '[background:rgba(255,255,255,0.04)]!',
    '[border:1px_solid_rgba(255,255,255,0.08)]!',
    '[&_strong]:[display:block]!',
    '[&_strong]:[color:#fff]!',
    '[&_strong]:[margin-bottom:4px]!',
    '[&_p]:[margin:0]!',
    '[&_p]:[font-size:15px]!',
    '[&_p]:[color:#d9e3f1]!',
    'max-[840px]:[grid-template-columns:1fr]!',
    'max-[840px]:[gap:8px]!',
    'max-[640px]:[border-radius:12px]!',
    'max-[640px]:[padding:12px_13px]!',
    'max-[640px]:[&_strong]:[font-size:17px]!',
  ].join(' '),
  'agenda-snapshot__time': [
    '[color:#8ecfc9]!',
    '[font-weight:700]!',
    '[font-size:15px]!',
    'max-[640px]:[font-size:14px]!',
  ].join(' '),
  'agenda-speaker-link': [
    '[color:inherit]!',
    '[font-style:italic]!',
    '[text-decoration:underline]!',
    '[text-underline-offset:3px]!',
    '[text-decoration-thickness:1.5px]!',
    '[&:hover]:[color:#b7e7de]!',
    '[&:focus-visible]:[color:#b7e7de]!',
  ].join(' '),
  'article-cover': [
    '[width:100%]!',
    '[border-radius:12px]!',
    '[margin-bottom:18px]!',
    '[display:block]!',
    '[max-height:420px]!',
    '[object-fit:cover]!',
    'max-[960px]:[max-height:340px]!',
    'max-[840px]:[max-height:280px]!',
    'max-[640px]:[max-height:220px]!',
    'max-[640px]:[margin-bottom:14px]!',
  ].join(' '),
  'article-info-box': [
    '[padding:14px_16px]!',
    '[border-radius:14px]!',
    '[border:1px_solid_rgba(255,255,255,0.1)]!',
    '[background:rgba(255,255,255,0.04)]!',
    'max-[640px]:[border-radius:12px]!',
    'max-[640px]:[padding:12px_13px]!',
  ].join(' '),
  'article-info-grid': [
    '[display:grid]!',
    '[grid-template-columns:repeat(3,_minmax(0,_1fr))]!',
    '[gap:12px]!',
    '[margin-bottom:18px]!',
    'max-[960px]:[grid-template-columns:1fr]!',
    'max-[640px]:[gap:10px]!',
    'max-[640px]:[margin-bottom:14px]!',
  ].join(' '),
  'article-meta': [
    '[color:#c8d3df]!',
    '[margin-bottom:16px]!',
    '[font-size:16px]!',
    'max-[640px]:[font-size:14px]!',
    'max-[640px]:[margin-bottom:14px]!',
  ].join(' '),
  'article-title': [
    '[margin:0_0_10px]!',
    '[padding-top:0]!',
    '[font-size:34px]!',
    '[line-height:1.22]!',
    '[color:#fff]!',
    '[word-break:break-word]!',
    'max-[840px]:[font-size:28px]!',
    'max-[640px]:[font-size:24px]!',
    'max-[640px]:[line-height:1.3]!',
    'max-[640px]:[margin-bottom:8px]!',
  ].join(' '),
  'back-news-link': [
    '[display:inline-block]!',
    '[margin-top:10px]!',
    '[color:#ffbe7a]!',
    '[font-weight:700]!',
    '[text-decoration:none]!',
    '[&:hover]:[text-decoration:underline]!',
    'max-[640px]:[margin-top:14px]!',
    'max-[640px]:[font-size:15px]!',
  ].join(' '),
  'container': [
    '[.publication-nav_&]:[display:block]!',
    '[.publication-nav_&]:[width:100%]!',
    '[.publication-nav_&]:[margin:0]!',
    '[.publication-nav_&]:[padding:0]!',
    '[.publication-nav_&_.ws-yr--navs]:[display:flex]!',
    '[.publication-nav_&_.ws-yr--navs]:[flex-direction:column]!',
    '[.publication-nav_&_.ws-yr--navs]:[gap:8px]!',
    '[.publication-nav_&_.ws-yr--navs]:[margin:0]!',
    '[.publication-nav_&_.ws-yr--navs]:[padding:0]!',
    '[.publication-nav_&_ul_li]:[list-style:none]!',
    '[.publication-nav_&_ul_li]:[display:flex]!',
    '[.publication-nav_&_ul_li]:[align-items:center]!',
    '[.publication-nav_&_ul_li]:[justify-content:center]!',
    '[.publication-nav_&_ul_li]:[min-height:42px]!',
    '[.publication-nav_&_ul_li]:[margin:0]!',
    '[.publication-nav_&_ul_li]:[padding:0]!',
    '[.publication-nav_&_ul_li]:[border-radius:12px]!',
    '[.publication-nav_&_ul_li]:[border:1px_solid_transparent]!',
    '[.publication-nav_&_ul_li]:[background:transparent]!',
    '[.publication-nav_&_ul_li]:[color:#c7d3ea]!',
    '[.publication-nav_&_ul_li]:[font-size:0.98rem]!',
    '[.publication-nav_&_ul_li]:[font-weight:650]!',
    '[.publication-nav_&_ul_li]:[transition:background-color_180ms_ease,_border-color_180ms_ease,_color_180ms_ease]!',
    '[.publication-nav_&_ul_li_a]:[display:inline-flex]!',
    '[.publication-nav_&_ul_li_a]:[align-items:center]!',
    '[.publication-nav_&_ul_li_a]:[justify-content:center]!',
    '[.publication-nav_&_ul_li_a]:[width:100%]!',
    '[.publication-nav_&_ul_li_a]:[min-height:42px]!',
    '[.publication-nav_&_ul_li_a]:[padding:0_10px]!',
    '[.publication-nav_&_ul_li_a]:[color:inherit]!',
    '[.publication-nav_&_ul_li_a]:[font-weight:700]!',
    '[.publication-nav_&_ul_li_a]:[letter-spacing:0.01em]!',
    '[.publication-nav_&_ul_li_a]:[text-decoration:none]!',
    '[.publication-nav_&_ul_li:hover]:[background-color:rgba(120,_145,_198,_0.13)]!',
    '[.publication-nav_&_ul_li:hover]:[border-color:rgba(162,_188,_242,_0.22)]!',
    '[.publication-nav_&_ul_li.active]:[background:rgba(122,_150,_214,_0.16)]!',
    '[.publication-nav_&_ul_li.active]:[border-color:rgba(166,_197,_255,_0.34)]!',
    '[.publication-nav_&_ul_li.active]:[color:#edf3ff]!',
    'max-[840px]:[.publication-nav_&_.ws-yr--navs]:[display:grid]!',
    'max-[840px]:[.publication-nav_&_.ws-yr--navs]:[grid-template-columns:repeat(2,_minmax(0,_1fr))]!',
    'max-[840px]:[.publication-nav_&_.ws-yr--navs]:[gap:10px]!',
    'max-[840px]:[.publication-nav_&_.ws-yr--navs]:[width:100%]!',
    'max-[840px]:[.publication-nav_&_.ws-yr--navs]:[margin:0]!',
    'max-[840px]:[.publication-nav_&_.ws-yr--navs]:[padding:0]!',
    'max-[840px]:[.publication-nav_&_ul_li]:[border-radius:999px]!',
    'max-[840px]:[.publication-nav_&_ul_li]:[border:1px_solid_rgba(157,_186,_255,_0.2)]!',
    'max-[840px]:[.publication-nav_&_ul_li]:[background:rgba(22,_28,_45,_0.66)]!',
    'max-[840px]:[.publication-nav_&_ul_li]:[backdrop-filter:blur(8px)]!',
    'max-[840px]:[.publication-nav_&_ul_li]:[-webkit-backdrop-filter:blur(8px)]!',
    'max-[840px]:[.publication-nav_&_ul_li_a]:[font-size:0.92rem]!',
    'max-[840px]:[.publication-nav_&_ul_li_a]:[color:#eaf2ff]!',
    'max-[840px]:[.publication-nav_&_ul_li.active]:[background:linear-gradient(100deg,_#7fe4ff,_#9cf9cf)]!',
    'max-[840px]:[.publication-nav_&_ul_li.active]:[border-color:rgba(147,_244,_230,_0.5)]!',
    'max-[840px]:[.publication-nav_&_ul_li.active]:[box-shadow:0_8px_18px_rgba(0,_0,_0,_0.22)]!',
    'max-[840px]:[.publication-nav_&_ul_li.active_a]:[color:#0a1424]!',
    'max-[1080px]:[.publication-nav_&]:[overflow-x:auto]!',
    'max-[1080px]:[.publication-nav_&]:[overflow-y:hidden]!',
    'max-[1080px]:[.publication-nav_&]:[padding:0_2px]!',
    'max-[1080px]:[.publication-nav_&]:[scrollbar-width:none]!',
    'max-[1080px]:[.publication-nav_&]:[-ms-overflow-style:none]!',
    'max-[1080px]:[.publication-nav_&::-webkit-scrollbar]:[display:none]!',
    'max-[1080px]:[.publication-nav_&_.ws-yr--navs]:[display:flex]!',
    'max-[1080px]:[.publication-nav_&_.ws-yr--navs]:[flex-wrap:nowrap]!',
    'max-[1080px]:[.publication-nav_&_.ws-yr--navs]:[gap:8px]!',
    'max-[1080px]:[.publication-nav_&_.ws-yr--navs]:[width:max-content]!',
    'max-[1080px]:[.publication-nav_&_.ws-yr--navs]:[min-width:100%]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[min-height:36px]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[min-width:68px]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[border-radius:999px]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[border:1px_solid_rgba(157,_186,_255,_0.16)]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[background:rgba(18,_24,_38,_0.72)]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[box-shadow:none]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[backdrop-filter:none]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[-webkit-backdrop-filter:none]!',
    'max-[1080px]:[.publication-nav_&_ul_li]:[flex:0_0_auto]!',
    'max-[1080px]:[.publication-nav_&_ul_li_a]:[min-height:36px]!',
    'max-[1080px]:[.publication-nav_&_ul_li_a]:[padding:0_12px]!',
    'max-[1080px]:[.publication-nav_&_ul_li_a]:[font-size:0.84rem]!',
    'max-[1080px]:[.publication-nav_&_ul_li_a]:[font-weight:700]!',
    'max-[1080px]:[.publication-nav_&_ul_li_a]:[letter-spacing:0.02em]!',
    'max-[1080px]:[.publication-nav_&_ul_li_a]:[color:#eaf2ff]!',
    'max-[1080px]:[.publication-nav_&_ul_li.active]:[background:rgba(136,_168,_235,_0.18)]!',
    'max-[1080px]:[.publication-nav_&_ul_li.active]:[border-color:rgba(168,_198,_255,_0.34)]!',
    'max-[1080px]:[.publication-nav_&_ul_li.active]:[box-shadow:none]!',
    'max-[1080px]:[.publication-nav_&_ul_li.active_a]:[color:#f3f8ff]!',
    'max-[720px]:[.publication-nav_&]:[padding-right:10px]!',
    'max-[720px]:[.publication-nav_&_ul_li]:[min-width:62px]!',
    'max-[720px]:[.publication-nav_&_ul_li_a]:[font-size:0.82rem]!',
  ].join(' '),
  'info-label': [
    '[display:block]!',
    '[margin-bottom:4px]!',
    '[color:#b7c8de]!',
    '[font-size:13px]!',
    '[letter-spacing:0.06em]!',
    '[text-transform:uppercase]!',
    'max-[640px]:[font-size:11px]!',
  ].join(' '),
  'info-value': [
    '[display:block]!',
    '[color:#fff]!',
    '[font-size:17px]!',
    '[font-weight:700]!',
    'max-[640px]:[font-size:15px]!',
  ].join(' '),
  'news-article-card': [
    '[background:rgba(255,255,255,0.06)]!',
    '[border:1px_solid_rgba(255,255,255,0.12)]!',
    '[border-radius:16px]!',
    '[padding:26px_24px]!',
    '[color:#f4f7fb]!',
    '[&_p]:[margin-bottom:12px]!',
    '[&_p]:[line-height:1.78]!',
    '[&_p]:[font-size:17px]!',
    '[&_h4]:[margin:24px_0_12px]!',
    '[&_h4]:[padding-top:0]!',
    '[&_h4]:[font-size:24px]!',
    '[&_h4]:[color:#fff]!',
    '[&_.ws-agenda-snapshot--item_p]:[margin:0]!',
    '[&_.ws-agenda-snapshot--item_p]:[font-size:15px]!',
    '[&_.ws-agenda-snapshot--item_p]:[line-height:1.78]!',
    'max-[640px]:[&_.ws-agenda-snapshot--item_p]:[line-height:1.72]!',
    '[&.news-article-card_h4]:[margin:24px_0_12px]!',
    'max-[840px]:[padding:18px_16px]!',
    'max-[840px]:[&_h4]:[font-size:21px]!',
    'max-[840px]:[&_p]:[font-size:16px]!',
    'max-[640px]:[border-radius:14px]!',
    'max-[640px]:[padding:16px_14px]!',
    'max-[640px]:[&_h4]:[margin:20px_0_10px]!',
    'max-[640px]:[&.news-article-card_h4]:[margin:20px_0_10px]!',
    'max-[640px]:[&_h4]:[font-size:20px]!',
    'max-[640px]:[&_p]:[font-size:15px]!',
    'max-[640px]:[&_p]:[line-height:1.72]!',
  ].join(' '),
  'news-section': [
    '[&_a]:[cursor:pointer]!',
    '[&_a:hover]:[text-decoration:none]!',
    '[&_a:hover]:[color:#bfdbdb]!',
    '[&_img]:[margin-top:30px]!',
    '[&_img]:[width:100%]!',
    '[&_img]:[height:auto]!',
    '[&_img]:[display:block]!',
    '[&_img]:[border-radius:4px]!',
    '[&_img]:[box-shadow:0_0_20px_rgba(0,0,0,0.4)]!',
    '[&_h3]:[font-size:44px]!',
    '[&_h3]:[line-height:1.3]!',
    '[&_h3]:[font-weight:700]!',
    '[&_h3]:[letter-spacing:1px]!',
    '[&_h3]:[color:#fff]!',
    '[padding:100px_0]!',
    '[width:100vw]!',
    '[height:100vh]!',
    '[display:block]!',
    '[overflow-x:hidden]!',
    '[overflow-y:auto]!',
    '[background-color:rgba(31,32,41,1)]!',
    '[-webkit-transition:all_300ms_linear]!',
    '[transition:all_300ms_linear]!',
    '[z-index:10]!',
    '[&_h4]:[margin-top:0.67em]!',
    '[&_h4]:[margin-bottom:0.67em]!',
    '[&_h4]:[margin-left:0]!',
    '[&_h4]:[margin-right:0]!',
    '[&_h4]:[font-weight:bold]!',
    '[&_h4]:[color:#fff]!',
    '[&_h4]:[text-align:left]!',
    '[&_a]:[display:inline-block]!',
    '[&_a]:[transition:transform_0.3s_ease]!',
    '[&_li]:[color:#fff]!',
    '[&_li]:[padding-top:5px]!',
    '[&_li]:[padding-bottom:5px]!',
    '[&_li]:[display:list-item]!',
    '[&_ul.sub-list]:[padding-bottom:10px]!',
    '[&_ul.sub-list]:[list-style-type:custom-list-style]!',
    '[&_li.nav-list]:[list-style-type:none]!',
    '[&_img]:[vertical-align:middle]!',
    'max-[640px]:[&_.container]:[padding-left:14px]!',
    'max-[640px]:[&_.container]:[padding-right:14px]!',
  ].join(' '),
  'organizer-brand': [
    '[min-width:0]!',
    '[display:grid]!',
    '[grid-template-rows:auto_auto]!',
    '[align-items:center]!',
    '[justify-items:center]!',
    '[min-height:0]!',
    '[padding:0]!',
    '[gap:10px]!',
    '[border-radius:0]!',
    '[background:transparent]!',
    '[border:0]!',
    '[overflow:hidden]!',
    '[text-align:center]!',
    'max-[640px]:[display:contents]!',
  ].join(' '),
  'organizer-brand--cma': [
    '[&.organizer-brand--cma]:[flex:1_1_0]!',
    '[&_.ws-organizer-brand--visual]:[background:transparent]!',
    '[&_.ws-organizer-brand--visual]:[min-height:0]!',
    '[&_.ws-organizer-brand--visual]:[padding:0]!',
    '[&_.ws-organizer-brand--visual]:[border:0]!',
    '[&_.ws-organizer-brand--visual]:[box-shadow:none]!',
    '[&_.ws-organizer-brand--visual]:[outline:0]!',
    '[&.organizer-brand--cma]:[background:transparent]!',
    '[&.organizer-brand--cma]:[border:0]!',
    '[&.organizer-brand--cma]:[box-shadow:none]!',
    '[&.organizer-brand--cma]:[outline:0]!',
    '[&_.ws-organizer-brand--logo]:[background:transparent]!',
    '[&_.ws-organizer-brand--logo]:[border:0]!',
    '[&_.ws-organizer-brand--logo]:[box-shadow:none]!',
    '[&_.ws-organizer-brand--logo]:[outline:0]!',
    '[&_.ws-organizer-brand--zh]:[font-size:14.5px]!',
  ].join(' '),
  'organizer-brand--critical-data': [
    '[&.organizer-brand--critical-data]:[flex:1_1_0]!',
    '[&_.ws-organizer-brand--visual]:[background:transparent]!',
    '[&_.ws-organizer-brand--visual]:[border-color:transparent]!',
    '[&_.ws-organizer-brand--visual]:[box-shadow:none]!',
    '[&_.ws-organizer-brand--visual]:[min-height:0]!',
    '[&_.ws-organizer-brand--visual]:[align-items:center]!',
    '[&_.ws-organizer-brand--visual]:[padding:0]!',
  ].join(' '),
  'organizer-brand--hkustgz': [
    '[&.organizer-brand--hkustgz]:[flex:1_1_0]!',
  ].join(' '),
  'organizer-brand--mc2': [
    '[&.organizer-brand--mc2]:[flex:1_1_0]!',
    '[&_.ws-organizer-brand--visual]:[background:transparent]!',
    '[&_.ws-organizer-brand--visual]:[border:0]!',
    '[&_.ws-organizer-brand--visual]:[box-shadow:none]!',
    '[&_.ws-organizer-brand--visual]:[outline:0]!',
    '[&.organizer-brand--mc2]:[background:transparent]!',
    '[&.organizer-brand--mc2]:[border:0]!',
    '[&.organizer-brand--mc2]:[box-shadow:none]!',
    '[&.organizer-brand--mc2]:[outline:0]!',
    '[&_.ws-organizer-brand--logo]:[background:transparent]!',
    '[&_.ws-organizer-brand--logo]:[border:0]!',
    '[&_.ws-organizer-brand--logo]:[box-shadow:none]!',
    '[&_.ws-organizer-brand--logo]:[outline:0]!',
  ].join(' '),
  'organizer-brand--mit': [
    '[&.organizer-brand--mit]:[flex:1_1_0]!',
  ].join(' '),
  'organizer-brand__en': [
    '[color:rgba(226,_236,_247,_0.78)]!',
    '[font-size:13px]!',
    '[line-height:1.45]!',
    '[font-weight:500]!',
    '[text-wrap:balance]!',
    '[display:none]!',
    'max-[640px]:[font-size:11px]!',
  ].join(' '),
  'organizer-brand__logo': [
    '[display:block]!',
    '[width:100%]!',
    '[max-width:100%]!',
    '[object-fit:contain]!',
    '[object-position:center]!',
  ].join(' '),
  'organizer-brand__logo--cma': [
  ].join(' '),
  'organizer-brand__logo--critical-data': [
    '[&.ws-organizer-brand--logo--critical-data]:[max-width:100%]!',
    '[&.ws-organizer-brand--logo--critical-data]:[object-position:center]!',
    '[&.ws-organizer-brand--logo--critical-data]:[padding:8px_12px]!',
    '[&.ws-organizer-brand--logo--critical-data]:[background:rgba(245,_247,_250,_0.96)]!',
    'max-[640px]:[&.ws-organizer-brand--logo--critical-data]:[padding:6px_10px]!',
  ].join(' '),
  'organizer-brand__logo--hkustgz': [
    '[&.ws-organizer-brand--logo--hkustgz]:[max-width:100%]!',
    '[&.ws-organizer-brand--logo--hkustgz]:[height:96px]!',
    'max-[640px]:[&.ws-organizer-brand--logo--hkustgz]:[height:58px]!',
  ].join(' '),
  'organizer-brand__logo--mc2': [
  ].join(' '),
  'organizer-brand__logo--mit': [
    '[&.ws-organizer-brand--logo--mit]:[max-width:100%]!',
    '[&.ws-organizer-brand--logo--mit]:[height:100px]!',
    '[&.ws-organizer-brand--logo--mit]:[object-position:center]!',
    'max-[640px]:[&.ws-organizer-brand--logo--mit]:[height:64px]!',
  ].join(' '),
  'organizer-brand__meta': [
    '[display:grid]!',
    '[gap:4px]!',
    '[width:100%]!',
    '[padding-top:2px]!',
    '[align-content:start]!',
    'max-[640px]:[grid-row:2]!',
    'max-[640px]:[align-self:start]!',
    'max-[640px]:[justify-self:center]!',
    'max-[640px]:[width:100%]!',
    'max-[640px]:[gap:2px]!',
    'max-[640px]:[padding-top:0]!',
    'max-[640px]:[text-align:center]!',
  ].join(' '),
  'organizer-brand__visual': [
    '[width:100%]!',
    '[min-height:0]!',
    '[display:flex]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[padding:0]!',
    '[border-radius:0]!',
    '[background:transparent]!',
    '[border:0]!',
    '[box-shadow:none]!',
    '[.organizer-pair--programs_&]:[min-height:0]!',
    'max-[640px]:[grid-row:1]!',
    'max-[640px]:[min-height:72px]!',
    'max-[640px]:[height:72px]!',
    'max-[640px]:[align-self:center]!',
    'max-[640px]:[justify-self:center]!',
    'max-[640px]:[width:100%]!',
  ].join(' '),
  'organizer-brand__zh': [
    '[color:#f2f6ff]!',
    '[font-size:14px]!',
    '[line-height:1.36]!',
    '[font-weight:600]!',
    '[text-wrap:balance]!',
    'max-[640px]:[font-size:12px]!',
  ].join(' '),
  'organizer-lockup': [
    '[display:grid]!',
    '[gap:16px]!',
    '[padding:0]!',
    '[background:transparent]!',
    '[border:0]!',
    '[box-shadow:none]!',
    'max-[640px]:[gap:12px]!',
  ].join(' '),
  'organizer-lockup__row': [
    '[display:grid]!',
    '[grid-template-columns:1fr]!',
    '[align-items:stretch]!',
    '[gap:0]!',
    'max-[640px]:[grid-template-columns:1fr]!',
    'max-[640px]:[gap:0]!',
  ].join(' '),
  'organizer-lockup__row--single': [
    '[&.ws-organizer-lockup--row--single]:[grid-template-columns:1fr]!',
    '[&.ws-organizer-lockup--row--single]:[gap:0]!',
    'max-[640px]:[&.ws-organizer-lockup--row--single]:[gap:12px]!',
  ].join(' '),
  'organizer-pair': [
    '[min-width:0]!',
    '[display:grid]!',
    '[grid-template-columns:minmax(0,_1fr)_auto_minmax(0,_1fr)]!',
    '[align-items:center]!',
    '[gap:16px]!',
    '[padding:18px_18px_16px]!',
    '[border-radius:16px]!',
    '[background:rgba(255,255,255,0.06)]!',
    '[border:1px_solid_rgba(255,255,255,0.08)]!',
    '[box-shadow:inset_0_1px_0_rgba(255,255,255,0.02)]!',
    'max-[640px]:[flex-basis:100%]!',
    'max-[640px]:[gap:10px]!',
    'max-[640px]:[padding:14px_12px]!',
  ].join(' '),
  'organizer-pair--institutions': [
    '[&.organizer-pair--institutions]:[grid-template-columns:minmax(0,_1.02fr)_auto_minmax(0,_1.08fr)_auto_minmax(0,_0.92fr)]!',
    '[&.organizer-pair--institutions]:[gap:14px]!',
    '[&.organizer-pair--institutions]:[align-items:center]!',
    'max-[640px]:[&.organizer-pair--institutions]:[grid-template-columns:minmax(0,_1fr)_28px_minmax(0,_1fr)_28px_minmax(0,_1fr)]!',
    'max-[640px]:[&.organizer-pair--institutions]:[grid-template-rows:72px_auto]!',
    'max-[640px]:[&.organizer-pair--institutions]:[align-items:center]!',
    'max-[640px]:[&.organizer-pair--institutions]:[gap:8px]!',
    'max-[640px]:[&.organizer-pair--institutions]:[padding:12px_10px]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(1)_.ws-organizer-brand--visual]:[grid-column:1]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(1)_.ws-organizer-brand--meta]:[grid-column:1]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(2)_.ws-organizer-brand--visual]:[grid-column:3]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(2)_.ws-organizer-brand--meta]:[grid-column:3]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(3)_.ws-organizer-brand--visual]:[grid-column:5]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(3)_.ws-organizer-brand--meta]:[grid-column:5]!',
    'max-[640px]:[&_>_.ws-organizer-pair--mark:nth-of-type(1)]:[grid-column:2]!',
    'max-[640px]:[&_>_.ws-organizer-pair--mark:nth-of-type(2)]:[grid-column:4]!',
  ].join(' '),
  'organizer-pair--schools': [
    '[&_.organizer-brand]:[min-height:0]!',
    '[&_.organizer-brand]:[padding:0]!',
    '[&_.organizer-brand]:[gap:8px]!',
    '[&_.ws-organizer-brand--meta]:[display:grid]!',
    '[&_.ws-organizer-brand--meta]:[gap:0]!',
    '[&_.ws-organizer-brand--meta]:[padding-top:4px]!',
    '[&.organizer-pair--schools]:[grid-template-columns:minmax(0,_1.16fr)_auto_minmax(0,_1.34fr)]!',
    '[&.organizer-pair--schools]:[gap:16px]!',
    '[&_.ws-organizer-brand--visual]:[min-height:0]!',
    '[&_.ws-organizer-brand--logo--mit]:[height:100px]!',
    '[&_.ws-organizer-brand--logo--hkustgz]:[height:96px]!',
    '[&_.ws-organizer-brand--zh]:[font-size:14.5px]!',
    '[&_.ws-organizer-brand--zh]:[line-height:1.3]!',
    'max-[640px]:[&.organizer-pair--schools]:[grid-template-columns:minmax(0,_1fr)_28px_minmax(0,_1fr)]!',
    'max-[640px]:[&.organizer-pair--schools]:[grid-template-rows:72px_auto]!',
    'max-[640px]:[&.organizer-pair--schools]:[align-items:center]!',
    'max-[640px]:[&.organizer-pair--schools]:[gap:8px]!',
    'max-[640px]:[&.organizer-pair--schools]:[padding:12px_10px]!',
    'max-[640px]:[&_.ws-organizer-brand--visual]:[grid-row:1]!',
    'max-[640px]:[&_.ws-organizer-brand--visual]:[min-height:72px]!',
    'max-[640px]:[&_.ws-organizer-brand--visual]:[height:72px]!',
    'max-[640px]:[&_.ws-organizer-brand--visual]:[align-self:center]!',
    'max-[640px]:[&_.ws-organizer-brand--visual]:[justify-self:center]!',
    'max-[640px]:[&_.ws-organizer-brand--visual]:[width:100%]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(1)_.ws-organizer-brand--visual]:[grid-column:1]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(1)_.ws-organizer-brand--meta]:[grid-column:1]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(2)_.ws-organizer-brand--visual]:[grid-column:3]!',
    'max-[640px]:[&_.organizer-brand:nth-of-type(2)_.ws-organizer-brand--meta]:[grid-column:3]!',
    'max-[640px]:[&_.ws-organizer-brand--logo--mit]:[height:64px]!',
    'max-[640px]:[&_.ws-organizer-brand--logo--hkustgz]:[height:58px]!',
    'max-[640px]:[&_>_.ws-organizer-pair--mark]:[grid-column:2]!',
  ].join(' '),
  'organizer-pair__mark': [
    '[display:flex]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[color:#3da1ff]!',
    '[font-size:30px]!',
    '[font-weight:300]!',
    '[line-height:1]!',
    'max-[640px]:[display:flex]!',
    'max-[640px]:[align-items:center]!',
    'max-[640px]:[justify-content:center]!',
    'max-[640px]:[grid-row:1]!',
    'max-[640px]:[align-self:center]!',
    'max-[640px]:[justify-self:center]!',
    'max-[640px]:[width:28px]!',
    'max-[640px]:[height:72px]!',
    'max-[640px]:[font-size:24px]!',
  ].join(' '),
  'registration-panel': [
    '[display:grid]!',
    '[grid-template-columns:minmax(0,_1.4fr)_204px]!',
    '[gap:24px]!',
    '[align-items:center]!',
    '[padding:20px]!',
    '[border-radius:16px]!',
    '[background:linear-gradient(135deg,_rgba(142,_207,_201,_0.12),_rgba(255,_190,_122,_0.08))]!',
    '[border:1px_solid_rgba(255,255,255,0.1)]!',
    '[margin-bottom:8px]!',
    'max-[960px]:[grid-template-columns:1fr]!',
    'max-[640px]:[border-radius:12px]!',
    'max-[640px]:[padding:12px_13px]!',
  ].join(' '),
  'registration-panel__lead': [
    '[margin-bottom:0]!',
    '[color:#ffffff]!',
    '[font-size:18px]!',
    '[font-weight:700]!',
    'max-[640px]:[font-size:16px]!',
    '[&.ws-registration-panel--lead]:[margin-bottom:0]!',
    '[&.ws-registration-panel--lead]:[font-size:18px]!',
    'max-[640px]:[&.ws-registration-panel--lead]:[font-size:16px]!',
    'max-[640px]:[&.ws-registration-panel--lead]:[line-height:1.72]!',
  ].join(' '),
  'registration-panel__link': [
    '[display:inline-flex]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[margin-top:16px]!',
    '[padding:11px_18px]!',
    '[border-radius:999px]!',
    '[background:#8ecfc9]!',
    '[color:#16202b]!',
    '[font-size:15px]!',
    '[font-weight:700]!',
    '[text-decoration:none]!',
    '[transition:transform_0.2s_ease,_box-shadow_0.2s_ease]!',
    '[&:hover]:[transform:translateY(-1px)]!',
    '[&:hover]:[box-shadow:0_12px_24px_rgba(7,_12,_24,_0.2)]!',
    'max-[640px]:[width:100%]!',
    'max-[640px]:[margin-top:14px]!',
    'max-[640px]:[font-size:14px]!',
    '[&.ws-registration-panel--link]:[display:inline-flex]!',
  ].join(' '),
  'registration-panel__qr': [
    '[width:100%]!',
    '[max-width:204px]!',
    '[justify-self:end]!',
    '[padding:0]!',
    '[border-radius:0]!',
    '[background:transparent]!',
    '[text-decoration:none]!',
    '[&_img]:[display:block]!',
    '[&_img]:[width:100%]!',
    '[&_img]:[height:auto]!',
    '[&_img]:[background:#ffffff]!',
    'max-[960px]:[justify-self:center]!',
    'max-[640px]:[max-width:184px]!',
  ].join(' '),
  'registration-panel__subtext': [
    '[margin-bottom:0]!',
    '[margin-top:14px]!',
    '[color:#c8d3df]!',
    '[font-size:14px]!',
    '[line-height:1.7]!',
    'max-[640px]:[font-size:13px]!',
    '[&.ws-registration-panel--subtext]:[margin-bottom:0]!',
    '[&.ws-registration-panel--subtext]:[font-size:14px]!',
    '[&.ws-registration-panel--subtext]:[line-height:1.7]!',
    'max-[640px]:[&.ws-registration-panel--subtext]:[font-size:13px]!',
    'max-[640px]:[&.ws-registration-panel--subtext]:[line-height:1.7]!',
  ].join(' '),
  'speaker-card-news': [
    '[overflow:hidden]!',
    '[border-radius:14px]!',
    '[background:rgba(255,255,255,0.04)]!',
    '[border:1px_solid_rgba(255,255,255,0.08)]!',
    '[cursor:pointer]!',
    '[-webkit-tap-highlight-color:transparent]!',
    '[scroll-margin-top:108px]!',
    '[transition:transform_0.22s_ease,_border-color_0.22s_ease,_background_0.22s_ease,_box-shadow_0.22s_ease]!',
    '[&:focus-visible]:[transform:translateY(-2px)]!',
    '[&:focus-visible]:[border-color:rgba(142,_207,_201,_0.34)]!',
    '[&:focus-visible]:[box-shadow:0_18px_36px_rgba(8,_12,_24,_0.24)]!',
    '[&:focus-visible]:[outline:none]!',
    '[@media(hover:hover)_and_(pointer:fine)]:[&:hover]:[transform:translateY(-2px)]!',
    '[@media(hover:hover)_and_(pointer:fine)]:[&:hover]:[border-color:rgba(142,_207,_201,_0.34)]!',
    '[@media(hover:hover)_and_(pointer:fine)]:[&:hover]:[box-shadow:0_18px_36px_rgba(8,_12,_24,_0.24)]!',
    '[@media(hover:hover)_and_(pointer:fine)]:[&:hover]:[outline:none]!',
    '[&.is-open]:[background:rgba(255,255,255,0.07)]!',
    '[&.is-open]:[border-color:rgba(142,_207,_201,_0.38)]!',
    '[&_h5]:[margin:0_0_4px]!',
    '[&_h5]:[padding-top:0]!',
    '[&_h5]:[font-size:17px]!',
    '[&_h5]:[font-weight:700]!',
    '[&_h5]:[color:#fff]!',
    '[&_h5]:[font-style:normal]!',
    '[&_h5]:[text-decoration:none]!',
    '[&.is-open_.ws-speaker-card-news--details]:[margin-top:10px]!',
    '[&.is-open_.ws-speaker-card-news--details]:[opacity:1]!',
    '[&.is-open_.ws-speaker-card-news--hint]:[color:#8ecfc9]!',
    '[&_.ws-speaker-card-news--role]:[font-size:14px]!',
    '[&_.ws-speaker-card-news--role]:[line-height:1.45]!',
    '[&_.ws-speaker-card-news--org]:[font-size:14px]!',
    '[&_.ws-speaker-card-news--org]:[line-height:1.45]!',
    '[&_.ws-speaker-card-news--hint]:[font-size:11px]!',
    '[&_.ws-speaker-card-news--hint]:[line-height:1.4]!',
    '[&_.ws-speaker-card-news--hint]:[letter-spacing:0.08em]!',
    '[&_.ws-speaker-card-news--bio]:[font-size:14px]!',
    '[&_.ws-speaker-card-news--bio]:[line-height:1.72]!',
    'max-[640px]:[border-radius:12px]!',
    'max-[640px]:[&_h5]:[font-size:16px]!',
    'max-[640px]:[&_.ws-speaker-card-news--role]:[font-size:13px]!',
    'max-[640px]:[&_.ws-speaker-card-news--org]:[font-size:13px]!',
    'max-[640px]:[&_.ws-speaker-card-news--hint]:[font-size:10px]!',
    'max-[640px]:[&_.ws-speaker-card-news--hint]:[letter-spacing:0.06em]!',
    'max-[640px]:[&_.ws-speaker-card-news--bio]:[font-size:13px]!',
    'max-[640px]:[&_.ws-speaker-card-news--bio]:[line-height:1.66]!',
  ].join(' '),
  'speaker-card-news__bio': [
    '[margin:0]!',
    '[padding-top:10px]!',
    '[border-top:1px_solid_rgba(255,255,255,0.08)]!',
    '[font-size:14px]!',
    '[line-height:1.72]!',
    '[color:#e3ebf7]!',
    '[white-space:normal]!',
    'max-[640px]:[font-size:13px]!',
    'max-[640px]:[line-height:1.66]!',
  ].join(' '),
  'speaker-card-news__body': [
    '[padding:12px_12px_14px]!',
    'max-[640px]:[padding:12px_12px_13px]!',
  ].join(' '),
  'speaker-card-news__details': [
    '[max-height:0]',
    '[margin-top:0]!',
    '[overflow:hidden]!',
    '[opacity:0]!',
    '[transition:max-height_0.28s_ease,_opacity_0.22s_ease,_margin-top_0.22s_ease]!',
  ].join(' '),
  'speaker-card-news__hint': [
    '[margin:10px_0_0]!',
    '[font-size:11px]!',
    '[line-height:1.4]!',
    '[letter-spacing:0.08em]!',
    '[text-transform:uppercase]!',
    '[color:#93a7c2]!',
    'max-[640px]:[font-size:10px]!',
    'max-[640px]:[letter-spacing:0.06em]!',
  ].join(' '),
  'speaker-card-news__image': [
    '[width:100%]!',
    '[aspect-ratio:1_/_1]!',
    '[object-fit:cover]!',
    '[display:block]!',
  ].join(' '),
  'speaker-card-news__image--pan-hui': [
    '[&.ws-speaker-card-news--image--pan-hui]:[object-fit:contain]!',
    '[&.ws-speaker-card-news--image--pan-hui]:[object-position:center_top]!',
    '[&.ws-speaker-card-news--image--pan-hui]:[background:#050506]!',
    '[&.ws-speaker-card-news--image--pan-hui]:[box-sizing:border-box]!',
  ].join(' '),
  'speaker-card-news__image--xianglilan': [
    '[&.ws-speaker-card-news--image--xianglilan]:[object-position:center_top]!',
  ].join(' '),
  'speaker-card-news__org': [
    '[margin:0]!',
    '[font-size:14px]!',
    '[line-height:1.45]!',
    '[color:#d2deee]!',
    '[margin-top:2px]!',
    'max-[640px]:[font-size:13px]!',
  ].join(' '),
  'speaker-card-news__role': [
    '[margin:0]!',
    '[font-size:14px]!',
    '[line-height:1.45]!',
    '[color:#9adad4]!',
    '[font-weight:700]!',
    'max-[640px]:[font-size:13px]!',
  ].join(' '),
  'speaker-grid-news': [
    '[display:grid]!',
    '[grid-template-columns:repeat(4,_minmax(0,_1fr))]!',
    '[gap:14px]!',
    '[margin-bottom:10px]!',
    'max-[960px]:[grid-template-columns:repeat(2,_minmax(0,_1fr))]!',
    'max-[840px]:[grid-template-columns:1fr]!',
    'max-[640px]:[gap:12px]!',
  ].join(' '),
  'sponsor-card': [
    '[padding:0_0_0_18px]!',
    '[background:transparent]!',
    '[border-top:0]!',
    '[border-right:0]!',
    '[border-bottom:0]!',
    '[border-left-width:2px]!',
    '[border-left-style:solid]!',
    '[border-left-color:rgba(142,_207,_201,_0.5)]!',
    '[box-shadow:none]!',
    '[&_h5]:[margin:0_0_10px]!',
    '[&_h5]:[padding-top:0]!',
    '[&_h5]:[font-size:20px]!',
    '[&.sponsor-card_h5]:[font-weight:700]!',
    '[&_h5]:[line-height:1.45]!',
    '[&_h5]:[color:#ffffff]!',
    '[&_h5]:[max-width:720px]!',
    '[&_p]:[margin:0_0_10px]!',
    '[&_p]:[color:#d9e3f1]!',
    '[&_p]:[font-size:15px]!',
    '[&_p]:[line-height:1.72]!',
    '[&_p:last-child]:[margin-bottom:0]!',
    '[&.sponsor-card_p]:[margin:0_0_10px]!',
    '[&.sponsor-card_p]:[font-size:15px]!',
    '[&.sponsor-card_p]:[line-height:1.72]!',
    '[&.sponsor-card_p:last-child]:[margin-bottom:0]!',
    'max-[640px]:[padding:0_0_0_15px]!',
    'max-[640px]:[&_p]:[font-size:15px]!',
    'max-[640px]:[&_p]:[line-height:1.72]!',
    'max-[640px]:[&_h5]:[font-size:18px]!',
    'max-[640px]:[&_h5]:[line-height:1.42]!',
  ].join(' '),
  'sponsor-card__header': [
    '[display:grid]!',
    '[grid-template-columns:minmax(210px,_246px)_minmax(0,_1fr)]!',
    '[gap:18px]!',
    '[align-items:center]!',
    '[margin-bottom:12px]!',
    '[&_.ws-sponsor-card--lead]:[margin:0]!',
    'max-[640px]:[grid-template-columns:1fr]!',
    'max-[640px]:[gap:12px]!',
  ].join(' '),
  'sponsor-card__heading': [
    '[min-width:0]!',
  ].join(' '),
  'sponsor-card__lead': [
    '[color:#f6fbff]!',
    '[font-weight:700]!',
    '[&.ws-sponsor-card--lead]:[color:#f6fbff]!',
  ].join(' '),
  'sponsor-card__logo': [
    '[display:block]!',
    '[width:auto]!',
    '[max-width:100%]!',
    '[object-fit:contain]!',
    '[margin:0_auto]!',
    '[&.ws-sponsor-card--logo]:[margin:0_auto]!',
  ].join(' '),
  'sponsor-card__logo--qingsong': [
  ].join(' '),
  'sponsor-card__logo--wsc': [
  ].join(' '),
  'sponsor-card__logo-frame': [
    '[min-height:94px]!',
    '[padding:14px_16px]!',
    '[border-radius:16px]!',
    '[background:linear-gradient(180deg,_rgba(255,255,255,0.98),_rgba(245,247,250,0.96))]!',
    '[border:1px_solid_rgba(255,255,255,0.48)]!',
    '[box-shadow:0_12px_26px_rgba(0,0,0,0.14)]!',
    '[display:flex]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[overflow:hidden]!',
    'max-[640px]:[max-width:252px]!',
    'max-[640px]:[min-height:88px]!',
  ].join(' '),
  'sponsor-grid': [
    '[display:grid]!',
    '[grid-template-columns:1fr]!',
    '[gap:18px]!',
  ].join(' '),
  'sponsor-showcase': [
    '[margin:20px_0_22px]!',
    '[padding:0]!',
    '[background:transparent]!',
    '[border:0]!',
    '[box-shadow:none]!',
    '[width:100%]!',
    '[display:flex]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    'max-[640px]:[padding:0]!',
    'max-[640px]:[padding-top:0]!',
  ].join(' '),
  'sponsor-showcase--after-venue': [
    '[&.sponsor-showcase--after-venue]:[margin:26px_0_18px]!',
    '[&.sponsor-showcase--after-venue]:[padding-top:18px]!',
    '[&.sponsor-showcase--after-venue]:[border-top:1px_solid_rgba(255,255,255,0.08)]!',
    '[&_.ws-sponsor-showcase--eyebrow]:[background:rgba(223,_246,_242,_0.05)]!',
    '[&_.ws-sponsor-showcase--eyebrow]:[border-color:rgba(223,_246,_242,_0.1)]!',
    '[&_.ws-sponsor-showcase--eyebrow]:[color:#e4f3ee]!',
    '[&_.ws-sponsor-showcase--deck]:[max-width:760px]!',
    '[&_.ws-sponsor-showcase--deck]:[color:#cfdae8]!',
    '[&_.sponsor-card]:[border-left-color:rgba(142,_207,_201,_0.34)]!',
    'max-[640px]:[&.sponsor-showcase--after-venue]:[padding-top:0]!',
  ].join(' '),
  'sponsor-showcase__deck': [
    '[margin:12px_0_0]!',
    '[color:#dce7f5]!',
    '[font-size:15px]!',
    '[line-height:1.74]!',
    '[max-width:880px]!',
    'max-[640px]:[font-size:15px]!',
    'max-[640px]:[line-height:1.72]!',
    '[&.ws-sponsor-showcase--deck]:[margin-bottom:0]!',
    '[&.ws-sponsor-showcase--deck]:[font-size:15px]!',
    '[&.ws-sponsor-showcase--deck]:[line-height:1.74]!',
    'max-[640px]:[&.ws-sponsor-showcase--deck]:[line-height:1.72]!',
  ].join(' '),
  'sponsor-showcase__eyebrow': [
    '[display:inline-flex]!',
    '[align-items:center]!',
    '[padding:6px_11px]!',
    '[border-radius:999px]!',
    '[background:rgba(255,255,255,0.07)]!',
    '[border:1px_solid_rgba(255,255,255,0.08)]!',
    '[color:#dff6f2]!',
    '[font-size:11px]!',
    '[font-weight:700]!',
    '[letter-spacing:0.08em]!',
    '[text-transform:uppercase]!',
  ].join(' '),
  'sponsor-showcase__intro': [
    '[margin-bottom:14px]!',
  ].join(' '),
  'track-card': [
    '[display:grid]!',
    '[align-items:center]!',
    '[justify-content:center]!',
    '[grid-template-rows:minmax(96px,_auto)_auto_1fr]!',
    '[align-content:start]!',
    '[padding:16px_16px_14px]!',
    '[border-radius:14px]!',
    '[background:rgba(255,255,255,0.04)]!',
    '[border:1px_solid_rgba(255,255,255,0.08)]!',
    '[&_h5]:[margin:0]!',
    '[&_h5]:[padding-top:0]!',
    '[&_h5]:[font-size:19px]!',
    '[&_h5]:[font-weight:700]!',
    '[&_h5]:[color:#fff]!',
    '[&_p:last-child]:[margin-bottom:0]!',
    'max-[960px]:[grid-template-rows:auto_auto_1fr]!',
    'max-[640px]:[border-radius:12px]!',
    'max-[640px]:[padding:12px_13px]!',
    'max-[640px]:[&_p]:[font-size:15px]!',
    'max-[640px]:[&_p]:[line-height:1.72]!',
    'max-[640px]:[&_h5]:[font-size:17px]!',
  ].join(' '),
  'track-card__body': [
    '[font-size:15px]!',
    '[margin-bottom:0]!',
  ].join(' '),
  'track-card__head': [
    '[margin-bottom:12px]!',
    'max-[960px]:[margin-bottom:10px]!',
    'max-[960px]:[min-height:0]!',
  ].join(' '),
  'track-card__lead': [
    '[margin-bottom:10px]!',
    '[font-size:15px]!',
    '[margin:0]!',
    '[&_strong]:[color:#fff]!',
  ].join(' '),
  'track-card__meta': [
    '[display:grid]!',
    '[gap:8px]!',
    '[min-height:78px]!',
    '[margin-bottom:12px]!',
    '[align-content:start]!',
    'max-[960px]:[margin-bottom:10px]!',
    'max-[960px]:[min-height:0]!',
  ].join(' '),
  'track-card__time': [
    '[margin-bottom:10px]!',
    '[font-size:15px]!',
    '[margin:0]!',
  ].join(' '),
  'track-grid': [
    '[display:grid]!',
    '[grid-template-columns:repeat(3,_minmax(0,_1fr))]!',
    '[gap:14px]!',
    '[margin-bottom:6px]!',
    'max-[960px]:[grid-template-columns:1fr]!',
  ].join(' '),
  'workshop-page-shell': [
    "[font-family:-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_'Helvetica_Neue',_Arial,_'Noto_Sans',_sans-serif,_'Apple_Color_Emoji',_'Segoe_UI_Emoji',_'Segoe_UI_Symbol',_'Noto_Color_Emoji']!",
    '[font-size:1rem]!',
    '[font-weight:400]!',
    '[line-height:1.5]!',
    '[text-align:left]!',
    '[width:100%]!',
    '[margin:0]!',
  ].join(' '),
  'workshop-locale-zh': [
    'max-[640px]:[&.workshop-locale-zh_.ws-agenda-snapshot--item_p]:[line-height:1.72]!',
  ].join(' '),
  'row': [
    '[margin-bottom:.5em]!',
  ].join(' '),
};

function classAlias(name: string): string {
  return name.includes('_') ? `ws-${name.replace(/_/g, '-')}` : '';
}

export function workshopClass(classNames: string): string {
  return classNames.split(/\s+/).flatMap((name) => [name, classAlias(name), WORKSHOP_STYLES[name] || '']).filter(Boolean).join(' ');
}
